---
# spell-checker:disable
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml|talismanrc)$
        # cloud-init file *must* begin with #cloud-config so do not include in
        # strict check
        exclude: cloud_config\.yml$
        types: [file, yaml]
        entry: yamllint --strict
      - id: yamllint
        name: yamllint-cloud-config
        files: cloud_config\.yml$
        entry: yamllint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by-required']
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/thoughtworks/talisman
    rev: scanwithrc
    hooks:
      - id: talisman-commit
